name: Doc (pdoc múltiplas versões + redirect)

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch atual
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para trocar de branch depois

      - name: Instalar pdoc
        run: pip install pdoc

      - name: Instalar streamlit
        run: pip install streamlit

      - name: Gerar doc da branch main (caso não seja ela)
        if: github.ref != 'refs/heads/main'
        run: |
          git fetch origin main
          git checkout origin/main
          mkdir -p docs-html/stable
          pdoc pages/utils --output-dir docs-html/stable
        working-directory: ${{ github.workspace }}

      - name: Gerar doc da branch dev (caso não seja ela)
        if: github.ref != 'refs/heads/dev'
        run: |
          git fetch origin dev
          git checkout origin/dev
          mkdir -p docs-html/dev
          pdoc pages/utils --output-dir docs-html/dev
        working-directory: ${{ github.workspace }}

      - name: Copiar index.html customizado (redirect para /stable/)
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [ $BRANCH_NAME = "dev" ]; then
              git fetch origin dev
              git checkout origin/dev
          fi
          cp .github/docs-template/redirect.html docs-html/index.html
        working-directory: ${{ github.workspace }}

      - name: Upload para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: docs-html

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
