name: Doc (pdoc → GitHub Pages)

on:
  push:
    branches: [ main, dev ]          # ou a branch que preferir
  workflow_dispatch:            # permite disparar manualmente

permissions:
  contents: read                # checkout
  pages: write                  # publicar no Pages
  id-token: write               # necessário p/ deploy

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar pdoc
        run: pip install pdoc

      - name: Determinar subpasta por branch
        id: vars
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "subdir=stable" >> $GITHUB_OUTPUT
            echo "is_main=true" >> $GITHUB_OUTPUT
          else
            echo "subdir=dev" >> $GITHUB_OUTPUT
            echo "is_main=false" >> $GITHUB_OUTPUT
          fi

      - name: Gerar HTML (pdoc)
        run: |
          mkdir -p docs-html/${{ steps.vars.outputs.subdir }}
          pdoc pages/utils --output-dir docs-html/${{ steps.vars.outputs.subdir }}

      - name: Adicionar index.html condicional
        run: |
        if [[ "${{ steps.vars.outputs.is_main }}" == "true" ]]; then
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./stable/" /><title>Redirecting...</title></head><body><p>Redirecting to <a href="./stable/">stable version</a>...</p></body></html>' > docs-html/index.html
        else
            echo '<!DOCTYPE html><html><head><title>Documentação</title></head><body><p>Documentação disponível em <a href="./dev/">/dev/</a> e <a href="./stable/">/stable/</a>.</p></body></html>' > docs-html/index.html
          fi
      
      - name: Verificar conteúdo final
        run: |
          ls -R docs-html || true
          echo "index.html:"
          cat docs-html/index.html || echo "index.html não encontrado"

      # empacota a pasta docs-html como artefato “static-site”
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-html

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   # ação oficial do GitHub
