name: Doc (pdoc → GitHub Pages com redirecionamento dinâmico)

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar pdoc
        run: pip install pdoc

      - name: Determinar nome da branch
        id: branch
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Gerar HTML (pdoc)
        run: |
          mkdir -p docs-html/${{ steps.branch.outputs.branch_name }}
          pdoc pages/utils --output-dir docs-html/${{ steps.branch.outputs.branch_name }}

      - name: Criar index.html com redirecionamento dinâmico
        run: |
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./${{ steps.branch.outputs.branch_name }}/" /><title>Redirecting...</title></head><body><p>Redirecionando para <a href="./${{ steps.branch.outputs.branch_name }}/">${{ steps.branch.outputs.branch_name }}</a>...</p></body></html>' > docs-html/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-html

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
