name: Doc (pdoc múltiplas versões + redirect)

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch atual
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para trocar de branch depois

      - name: Instalar pdoc
        run: pip install pdoc

      - name: Cleanup
        run: rm -rf docs-html

      - name: Gerar doc da branch atual
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          mkdir -p docs-html/$BRANCH_NAME
          pdoc pages/utils --output-dir docs-html/$BRANCH_NAME
          

      - name: debug caminho
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "docs-html/${BRANCH_NAME}"
      
      - name: debug working-directory
        run: echo ${{ github.workspace}}
      
      - name: debug where i am
        run: pwd
      
      - name: debug what there
        run: ls

      - name: Gerar doc da branch main (caso não seja ela)
        if: github.ref != 'refs/heads/main'
        run: |
          git fetch origin main
          git checkout origin/main
          mkdir -p docs-html/stable
          pdoc pages/utils --output-dir docs-html/stable
        working-directory: ${{ github.workspace }}

      - name: Gerar doc da branch dev (caso não seja ela)
        if: github.ref != 'refs/heads/dev'
        run: |
          git fetch origin dev
          git checkout origin/dev
          mkdir -p docs-html/dev
          pdoc pages/utils --output-dir docs-html/dev
        working-directory: ${{ github.workspace }}

      - name: Criar index.html (redirect para /stable/)
        run: |
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./stable/" /><title>Redirecting...</title></head><body><p>Redirecting to <a href="./stable/">stable</a>...</p></body></html>' > docs-html/index.html

      - name: Upload para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: docs-html
          if-no-files-found: error

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4