name: Doc (pdoc múltiplas versões + redirect)

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      modo:
        description: "Modo de execução"
        required: false
        default: "normal"
        type: choice
        options: [normal, dry-run]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar modo de execução
        run: echo "Modo: ${{ github.event.inputs.modo || 'normal' }}"

      - name: Checkout branch atual
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar pdoc
        run: pip install pdoc

      - name: Gerar doc da branch atual
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          mkdir -p docs-html/$BRANCH_NAME
          pdoc pages/utils --output-dir docs-html/$BRANCH_NAME

      - name: Gerar doc da branch main (caso não seja ela)
        if: github.ref != 'refs/heads/main'
        run: |
          git fetch origin main
          git checkout origin/main
          mkdir -p docs-html/stable
          pdoc pages/utils --output-dir docs-html/stable
        working-directory: ${{ github.workspace }}

      - name: Gerar doc da branch dev (caso não seja ela)
        if: github.ref != 'refs/heads/dev'
        run: |
          git fetch origin dev
          git checkout origin/dev
          mkdir -p docs-html/dev
          pdoc pages/utils --output-dir docs-html/dev
        working-directory: ${{ github.workspace }}

      - name