name: Gerar Documentação

on:
  push:
    branches:
      - main  # ou a branch que você utiliza

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
      - name: Gerar documentação
        run: |
          pdoc flames_utils.py -o docs
      - name: Commit e push da documentação
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Atualizar documentação"
          git push
